### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by jorgeflores** [yusukeshibata/express-fingerprint#5]
Hi,
I have installed this library but I'm having this error when I tried to run my app. I'm using node v8.9.4 and npm 5.6.0. Do you have any idea about it?

Thank you!

D:\Proyectos\travelxite\Projects\travelertoken-backend\node\tlt-backend\node_modules\express-fingerprint\lib\parameter\geoip.js:16
  var _ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee(req) {
                               ^

ReferenceError: regeneratorRuntime is not defined
    at D:\Proyectos\travelxite\Projects\travelertoken-backend\node\tlt-backend\node_modules\express-fingerprint\lib\parameter\geoip.js:16:32
    at Object.<anonymous> (D:\Proyectos\travelxite\Projects\travelertoken-backend\node\tlt-backend\node_modules\express-fingerprint\lib\parameter\geoip.js:40:2)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Proyectos\travelxite\Projects\travelertoken-backend\node\tlt-backend\node_modules\express-fingerprint\lib\parameter\index.js:7:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Proyectos\travelxite\Projects\travelertoken-backend\node\tlt-backend\node_modules\express-fingerprint\lib\index.js:14:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Proyectos\travelxite\Projects\travelertoken-backend\node\tlt-backend\node_modules\express-fingerprint\index.js:1:80)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Proyectos\travelxite\Projects\travelertoken-backend\node\tlt-backend\app.js:19:21)
Program node --inspect ./bin/www exited with code 1

**Comment by marverix** [comment]
https://github.com/yusukeshibata/express-fingerprint/pull/6

**Comment by yusukeshib** [comment]
Fixed with v1.1.2
